services:
  postgres:
    image: 'postgres:14.5'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nftweb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # 管理介面 http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # 持久化資料（包含 mnesia 資料庫等）
      - rabbitmq_data:/var/lib/rabbitmq

  mongo:
    image: 'mongo:7.0'
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      # 使用 mongosh 對 admin DB 做 ping
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admin", "-p", "password", "--authenticationDatabase", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mongodata:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI http://localhost:8025
    healthcheck:
      # 確認 Web UI 可回應；wget 由 busybox 提供
      test: [ "CMD", "wget", "-qO-", "http://localhost:8025/api/v2/messages" ]
      interval: 10s
      timeout: 5s
      retries: 5

  goapp:
    build: .
    container_name: goapp
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - CONFIG_PATH=configs/config.yaml
      - HTTP_ADDR=:8080
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  rabbitmq_data:
  pgdata:
  mongodata:
