services:
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
