-- 建立 users table (若不存在才建立)
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    wallet_address VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 插入資料，如果 email 已存在則略過
INSERT INTO users (first_name, last_name, email, password, wallet_address)
VALUES (
  'Peter',
  'Chen',
  'test@example.com',
  '$2a$14$wVsaPvJnJJsomWArouWCtusem6S/.Gauq/GjOIEHpyh2DAMmso1wy',
  '0x1deAe8b25D834F31B88058bc137E8e80E54f1F86'
),
(
  'Andy',
  'Lin',
  'test2@example.com',
  '$2a$14$wVsaPvJnJJsomWArouWCtusem6S/.Gauq/GjOIEHpyh2DAMmso1wy',
  '0xA278Aa560B6A1D2ED46F7faf724C67E9eF20B2EA'
)
ON CONFLICT (email) DO NOTHING;

-- 建立 nft table (若不存在才建立)
CREATE TABLE IF NOT EXISTS nft (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    image VARCHAR(255)
);

-- 插入資料
INSERT INTO nft
VALUES (
  '0',
  'AIRA',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/0.jpg'
),
(
  '1',
  'MOMO',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/1.jpg'
),
(
  '2',
  'OKARUN',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/2.jpg'
),
(
  '3',
  'TURBO GRANNY',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/3.jpg'
),
(
  '4',
  'JI JI',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/4.jpg'
),
(
  '5',
  'SERPOIANS',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/5.jpg'
),
(
  '6',
  'OKARUN(TRANS.)',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/6.jpg'
),
(
  '7',
  'SEIKO',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/7.jpg'
),
(
  '8',
  'TURBO GRANNY(MIS.)',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/8.jpg'
),
(
  '9',
  'Egg box',
  'bafkreiek5l646yuqixcqxaeengimuub2jcd3zqywvlty2725ecgyjntq44'
)